### ISSUE TITLE
How to set a format whitelist manually ?

### ISSUE THREAD

**Issue by fcisio** [cloudinary/js-url-gen#424]
Hi, I have a weird issue where only some of my images with `autoFormat()` are served as `jp2` which just do not display at all in browsers.

To fix this I want to set a format whitelist manually

I've tried:
- `image.delivery(format('avif:webp:png:jpg'))`
- `image.delivery(format(['avif', 'webp', 'png', 'jpg']))`
- `image.delivery(format([avif(), webp(), png(), jpg()]))`

Is there a way to do this?
Else is that a possible feature that could be implemented?

**Comment by patrick-tolosa** [comment]
Hey @fcisio ,

Using the `format()` action does not actually whitelist the format, but instead sets it (I.E forces the asset to return with a given format).

This behaviour is most commonly seen when you use an emulator, for example in Chrome, to emulate an iOS device.
Cloudinary uses the user-agent to determine that jp2 can be safely served, but Chrome cannot handle the jp2 format, resulting in the error you're seeing.

A real user, using Chrome, will never receive `jp2` as a format - if that is the case please provide the URL you're using, or if you wish open a customer support ticket from your Cloudinary account.

Aside from that, from what I understand, your feature suggestion is "Provide the ability to define which formats are served using autoFormat()". is that correct?

**Comment by fcisio** [comment]
Thanks for the clarifications. Knowing that `jp2` should not be served in real-life situations is satisfactory.

Regarding your last point, yes exactly! I think that `autoFormat()` should allow for an array of formats to act as a whitelist.
Allowing users to define their own "auto" formats.

> Not understanding the issue with jp2, I've basically added some logic in `format()` instead.
`format(supportsWebP ? 'webp' : 'jpg' )`

**Comment by patrick-tolosa** [comment]
Glad to hear.

Please remember that the whole point of autoFormat is that you, as a developer, don't need to concern yourself with what formats are valid or not.

Instead of you keeping track of what new formats exist (for example, what about `avif` why use webp?), Cloudinay takes care of it for you.

If you want, you can use a specific format manually:

```
Delivery(format('png')) and you can condition it yourself. 
```

I'm closing this issue as it seems resolved, but feel free to continue the discussion here.
