### ISSUE TITLE
Accessing URL of a raw file

### ISSUE THREAD

**Issue by prabhatmyadbox** [cloudinary/js-url-gen#529]
Hi!
Is there a way to get URL of a raw file using public_id, similar to `cloudinary.url()` in `cloudinary-core`?

Thanks!
Prabs

**Comment by dannyv-cloudinary** [comment]
Hi Prabs.

You can actually use the url() helper method in cloudinary-core too. Say you had a file called styles.css in your account under the site_files folder. To generate the URL for with with cloudinary-core, you would use
`cloudinary.url("site_files/styles.css", {resource_type: "raw"})`

I've put together a quick demo for you here: https://jsfiddle.net/dannyv_cloudinary/dmqry4c3/

**Comment by prabhatmyadbox** [comment]
Thanks for the response. I am currently using `cloudinary-core` and its `url` method. However,  since `cloudinary-core` is considered legacy, I am trying to use `js-url-gen` instead. So, i wanted to know if there is an equivalent methos to `url` in this new library.

**Comment by francistagbo** [comment]
Hi Prabs,

You can use our setAssetType('raw') method. For example:

`new CloudinaryImage('sample', {cloudName: 'demo'}).setAssetType('raw').toURL();`

Could you please try and let me know how it goes?

Thanks,
Francis

**Comment by prabhatmyadbox** [comment]
That did the job. Thank you Francis
