### ISSUE TITLE
`SyntaxError` when used with `jest`

### ISSUE THREAD

**Issue by tux4** [cloudinary/js-url-gen#539]
Hi,
I am using `@cloudinary/url-gen` version `1.8.0` in with TypeScript with `jest`. I don’t get this error in the application but while running the test I get the following error:  

    
     RUNS  app/ui/universal/header/header.test.tsx // <— This is my application file
    Jest encountered an unexpected token
    
    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
    
    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
    
    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html
    
    Details:
    
    /Users/website/node_modules/@cloudinary/url-gen/actions/resize.js:52
    import { ResizePadAction } from "./resize/ResizePadAction.js";
    ^^^^^^
    
    SyntaxError: Cannot use import statement outside a module
        at new Script (node:vm:100:7)
        at Runtime.createScriptFromCode (/Users//website/node_modules/jest-runtime/build/index.js:1350:14)
        at Runtime._execModule (/Users/website/node_modules/jest-runtime/build/index.js:1245:25)
        at Runtime._loadModule (/Users/website/node_modules/jest-runtime/build/index.js:898:12)
        at Runtime.requireModule (/Users/website/node_modules/jest-runtime/build/index.js:746:10)
        at Runtime.requireModuleOrMock (/Users/website/node_modules/jest-runtime/build/index.js:919:21)
        at Object.<anonymous> (/Users/website/app/ui/shopping/SinglePageCatalog/ShelfPromotionVideo.tsx:3:1)
        at Runtime._execModule (/Users/website/node_modules/jest-runtime/build/index.js:1299:24)
        at Runtime._loadModule (/Users/website/node_modules/jest-runtime/build/index.js:898:12)
        at Runtime.requireModule (/Users/website/node_modules/jest-runtime/build/index.js:746:10)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I tried making the jest and babel config changes described here - https://github.com/cloudinary/js-url-gen#testing-with-jest   But then I started getting into more errors after this, now starting from my application code -    

     FAIL  app/selectors/selector.test.ts
      ● Test suite failed to run
    
        Jest encountered an unexpected token
    
        This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
    
        By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
    
        Here's what you can do:
         • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
         • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
         • If you need a custom transformation specify a "transform" option in your config.
         • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    
        You'll find more details and examples of these config options in the docs:
        https://jestjs.io/docs/en/configuration.html
    
        Details:
    
        /Users/website/app/test/jest-mock-setup.ts:2
        import "jest-styled-components";
        ^^^^^^
    
        SyntaxError: Cannot use import statement outside a module
    
          at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)

  I am not sure how to fix this. Do you folks have any clue?   Here is some more info about the my platform:

    "@cloudinary/react": "^1.4.2",
    "@cloudinary/url-gen": "^1.8.0",      "babel-jest": "^26.6.3",     "jest": "^26.6.3",
    "typescript": "~4.5.5",

Thanks,

**Comment by wissam-khalili** [comment]
Hi,

We have further looked into your issue, and it seems that it isn't related to the SDK but to the environment.
I have found this article: https://bobbyhadz.com/blog/typescript-jest-cannot-use-import-statement-outside-module, which might help you with this issue.

Please let us know if there is anything else we can assist with.

Thanks

**Comment by jamielockie** [comment]
Hello!

I seem to be having a very similar issue to @tux4 . I have read the article posted above and tried those adjustments to no avail. We have over 200 other tests with many external dependencies running in our codebase. This issue is isolated to components using this library.

When importing transformation functions from the `@cloudinary/url-gen` package to use with the `@cloudinary/react` SDK, the tests are unable to run and throw a syntax error, despite setting up our configs as directed in the [testing with jest](https://github.com/cloudinary/js-url-gen#Testing-with-jest) section of the docs.

The Error:
```
Summary of all failing tests
 FAIL  src/components/molecules/ml-cloudinary-video/__tests__/ml-cloudinary-video.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/jamielockie/sites/apply/kraft/heinz-app/node_modules/@cloudinary/url-gen/actions/resize.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { Resize } from "@cloudinary/transformation-builder-sdk/actions";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 |
      3 | import { AdvancedImage, AdvancedVideo } from '@cloudinary/react';
    > 4 | import { thumbnail } from '@cloudinary/url-gen/actions/resize';
```
Imports in React Component:
```
import { AdvancedImage, AdvancedVideo } from '@cloudinary/react';
import { thumbnail } from '@cloudinary/url-gen/actions/resize';
import { autoGravity } from '@cloudinary/url-gen/qualifiers/gravity';
```

babel.config.js
```module.exports = {
  presets: ['next/babel'],
  plugins: [
    'inline-react-svg',
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-private-methods', { loose: true }],
  ],
};
```

jest.config.js
```
module.exports = {
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
    '<rootDir>/node_modules/@cloudinary/url-gen': 'babel-jest',
  },
  transformIgnorePatterns: [
        `/node_modules/(?!${ignoredModules})`,
        '<rootDir>/node_modules/(?!@cloudinary/url-gen)'
    ],
  }
}
```

dependencies
```
"@cloudinary/react": "^1.4.2
"@cloudinary/url-gen": "^1.8.0,
"babel-jest": "^27.5.1",

```


Any help would be much appreciated! Thank you.

**Comment by lbendavid-cloudinary** [comment]
Hi @tux4 @jamielockie
Please try the following in Jest config file:
```
{
  "transformIgnorePatterns": ["/node_modules/(?!(@cloudinary/url-gen|@cloudinary/transformation-builder-sdk))"]
}
```
And see if it helps, we would like to hear from you.
Thanks!

**Comment by lbendavid-cloudinary** [comment]
Alternatively you can try to upgrade Jest to v28 or later, And then you won't need the ```transformIgnorePatterns``` definition at all.

**Comment by jamielockie** [comment]
Hi @lbendavid-cloudinary, 

Unfortunately that `transformIgnorePatterns` update did not solve the issue. We're also not in a position to update Jest, at the moment...

@tux4 would you happen to have an example of your workaround that you would be willing to share?
