### ISSUE TITLE
Replacing images currently stored in cloudinary

### ISSUE THREAD

**Issue by elleryvelope** [cloudinary/js-url-gen#544]
Hello. We've been implementing the url-gen package for an app that we're currently developing. I've been using it to grab some images we get from an external server provided to us by our client and transforming them with Cloudinary. However, we've been noticing that when our client updates the images, without changing the image's name, the url-gen package continues to deliver the same image that'd been stored before in our cloudinary account.

Simply put, is there a way to delete or replace an image that has been previously generated with url-gen? Or is it recommended to use another cloudinary package to handle this?

I'll add a sample of how we're using cloudinary below

```
const cld = new Cloudinary({
  cloud: {
    cloudName: '<our token>',
  },
})

export function resizeCarouselImage(url: string, width: number, height: number, radius: number) {
  const resizedImage = cloudinaryImage(url, width, height)
    .roundCorners(byRadius(radius))
    .toURL()
  return resizedImage
}

function cloudinaryImage(url: string, width: number, height: number) {
  const cldImage = cld.image(url).setDeliveryType('fetch')
  const modifiedImage = cldImage.resize(
    fit()
      .width(width)
      .height(height)
  )
  return modifiedImage
}

```

**Comment by epasos573** [comment]
Hi @elleryvelope, you would need to invalidate the asset using one of our Backend SDKs (e.g., through the explicit method). For example, using the [Node SDK integration](https://cloudinary.com/documentation/node_integration):

```
cloudinary.v2.uploader
.explicit("target_publicid", 
  { type: "upload",
     invalidate: true
  }).then(result=>console.log(result));
```

By doing the invalidation, the CDN cached copy of the asset will be purged and the newer version will be delivered when the asset is requested again.
